In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("/workspaces/demo-devcontainer/src/holding.csv", nrows=100000)

In [5]:
df

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
99995,306412e,2020/12/31,170,2021/01/08,0.07,11420000.0,1.465875e+07,GEORGIA ST 5.000% 01-Feb-2030,373385AN
99996,306412e,2020/12/31,171,2021/01/08,0.07,11800000.0,1.458421e+07,"California, State of 5% 01-OCT-2025",13063DQE
99997,306412e,2020/12/31,171,2021/01/08,0.07,12000000.0,1.459415e+07,Massachusetts School Building Authority 5% 15-...,576000YJ
99998,306412e,2020/12/31,173,2021/01/08,0.07,11485000.0,1.449755e+07,Massachusetts Water Resources Authority 5% 01-...,576051PH
99999,306412e,2020/12/31,174,2021/01/08,0.07,12655000.0,1.449369e+07,Contra Costa Community College District 5% 01-...,212204HD

In [6]:
df.head()

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10

In [7]:
df.head(20)

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
5,2998623,2020/11/30,6,2021/01/08,1.64,866386.0,1.997713e+08,GOLDMAN SACHS GROUP INC,38141G10
6,2998623,2020/11/30,7,2021/01/08,1.63,2194727.0,1.976352e+08,C S X CORP,12640810
7,2998623,2020/11/30,8,2021/01/08,1.60,5045923.0,1.939653e+08,AMERICAN INTERNATIONAL GROUP INC,02687478
8,2998623,2020/11/30,9,2021/01/08,1.59,1403360.0,1.937619e+08,P N C FINANCIAL SERVICES GRP INC,69347510
9,2998623,2020/11/30,10,2021/01/08,1.54,3065766.0,1.874409e+08,C B R E GROUP INC,12504L10
10,2998623,2020/11/30,11,2021/01/08,1.54,186854700.0,1.869642e+08,US Treasury 0.375% 30-Nov-2025,91282CAZ
11,2998623,2020/11/30,12,2021/01/08,1.52,6737689.0,1.842758e+08,WELLS FARGO & CO NEW,94974610
12,2998623,2020/11/30,13,2021/01/08,1.50,3968733.0,1.827205e+08,JOHNSON CONTROLS INTL PLC,G5150210
13,2998623,2020/11/30,14,2021/01/08,1.50,182211000.0,1.821434e+08,United States of America (Government) .125% 30...,91282CAX
14,2998623,2020/11/30,15,2021/01/08,1.50,583989.0,1.819243e+08,ANTHEM INC,03675210
15,2998623,2020/11/30,16,2021/01/08,1.46,1208147.0,1.778030e+08,QUALCOMM INC,74752510
16,2998623,2020/11/30,17,2021/01/08,1.43,1161825.0,1.735186e+08,GENERAL DYNAMICS CORP,36955010
17,2998623,2020/11/30,18,2021/01/08,1.39,5156744.0,1.684193e+08,CITIZENS FINANCIAL GROUP INC,17461010
18,2998623,2020/11/30,19,2021/01/08,1.36,165210387.0,1.652104e+08,Invesco Treasury Portfolio;Institutional,82525240
19,2998623,2020/11/30,20,2021/01/08,1.31,3420381.0,1.587741e+08,TRUIST FINANCIAL CORP,89832Q10

In [8]:
df.tail(20)

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
99980,306412e,2020/12/31,152,2021/01/08,0.07,13005000.0,15005646.0,New York City Transitional Finance Authority 4...,64971XDT
99981,306412e,2020/12/31,152,2021/01/08,0.07,15000000.0,15000590.0,"New York, City of .08% 01-DEC-2047",64966ML9
99982,306412e,2020/12/31,152,2021/01/08,0.07,11350000.0,15004511.0,"Connecticut, State of 5% 01-MAY-2037",207758A2
99983,306412e,2020/12/31,152,2021/01/08,0.07,15000000.0,15000980.0,Ohio State University .05% 01-JUN-2035,677632NX
99984,306412e,2020/12/31,159,2021/01/08,0.07,12500000.0,14985347.0,New York City Municipal Water Finance Authorit...,64972GXP
99985,306412e,2020/12/31,159,2021/01/08,0.07,14615000.0,14970632.0,GWINNETT CNTY GA SCH DIST 5.000% 01-Feb-2021,403755U4
99986,306412e,2020/12/31,161,2021/01/08,0.07,12500000.0,14922333.0,Dallas Area Rapid Transit 5% 01-DEC-2048,235241RV
99987,306412e,2020/12/31,162,2021/01/08,0.07,11190000.0,14895457.0,"California, State of 5% 01-APR-2033",13063DLM
99988,306412e,2020/12/31,162,2021/01/08,0.07,12000000.0,14888773.0,State of New Jersey 4% 01-JUN-2031,646039YQ
99989,306412e,2020/12/31,164,2021/01/08,0.07,10500000.0,14821590.0,North Texas Tollway Authority 5% 01-JAN-2034,66285WWH
99990,306412e,2020/12/31,164,2021/01/08,0.07,11730000.0,14821285.0,Commonwealth of Massachusetts 5% 01-JUN-2043,57604TFL
99991,306412e,2020/12/31,164,2021/01/08,0.07,12400000.0,14818124.0,Grand Parkway Transportation Corp 4% 01-OCT-2045,38611TCB
99992,306412e,2020/12/31,167,2021/01/08,0.07,12485000.0,14786901.0,"New York, City of 5% 01-AUG-2024",64966MJH
99993,306412e,2020/12/31,168,2021/01/08,0.07,12705000.0,14714973.0,CLARK CNTY NEV 4.000% 01-Jun-2038,180848TA
99994,306412e,2020/12/31,169,2021/01/08,0.07,14260000.0,14669975.0,CHICAGO ILL O HARE INTL ARPT REV 5.750% 01-Jan...,167593F9
99995,306412e,2020/12/31,170,2021/01/08,0.07,11420000.0,14658750.0,GEORGIA ST 5.000% 01-Feb-2030,373385AN
99996,306412e,2020/12/31,171,2021/01/08,0.07,11800000.0,14584210.0,"California, State of 5% 01-OCT-2025",13063DQE
99997,306412e,2020/12/31,171,2021/01/08,0.07,12000000.0,14594147.0,Massachusetts School Building Authority 5% 15-...,576000YJ
99998,306412e,2020/12/31,173,2021/01/08,0.07,11485000.0,14497554.0,Massachusetts Water Resources Authority 5% 01-...,576051PH
99999,306412e,2020/12/31,174,2021/01/08,0.07,12655000.0,14493687.0,Contra Costa Community College District 5% 01-...,212204HD

In [9]:
df[100:105]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
100,2998623,2020/11/30,101,2021/01/08,0.21,17148000.0,25722000.00,ON Semiconductor Corp 1.000% 01-Dec-2020,682189AK
101,2998623,2020/11/30,102,2021/01/08,0.21,14118000.0,25519881.75,Zillow Group Inc 2.75% 15-MAY-2025,98954MAH
102,2998623,2020/11/30,103,2021/01/08,0.20,20716000.0,24879675.69,Live Nation Entertainment Inc 2.5% 15-MAR-2023,538034AQ
103,2998623,2020/11/30,104,2021/01/08,0.20,17930000.0,24866668.75,Neurocrine Biosciences Inc 2.25% 15-MAY-2024,64125CAD
104,2998623,2020/11/30,105,2021/01/08,0.20,24298000.0,24546760.01,Southern Co 2.35% 01-JUL-2021,842587CS

In [10]:
df.loc[[1, 3, 5], :]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
5,2998623,2020/11/30,6,2021/01/08,1.64,866386.0,1.997713e+08,GOLDMAN SACHS GROUP INC,38141G10

In [12]:
df.loc[1:5, :]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
5,2998623,2020/11/30,6,2021/01/08,1.64,866386.0,1.997713e+08,GOLDMAN SACHS GROUP INC,38141G10

In [14]:
df.loc[1:5, ["portno", "report_dt"]]

    portno   report_dt
1  2998623  2020/11/30
2  2998623  2020/11/30
3  2998623  2020/11/30
4  2998623  2020/11/30
5  2998623  2020/11/30

In [17]:
df.iloc[1:5, [0, 1]]

    portno   report_dt
1  2998623  2020/11/30
2  2998623  2020/11/30
3  2998623  2020/11/30
4  2998623  2020/11/30

In [18]:
df.columns

Index(['portno', 'report_dt', 'security_rank', 'eff_dt', 'percent_tna',
       'nbr_shares', 'market_val', 'security_name', 'cusip'],
      dtype='object')

In [20]:
df.shape

(100000, 9)

In [21]:
df.dtypes

portno            object
report_dt         object
security_rank      int64
eff_dt            object
percent_tna      float64
nbr_shares       float64
market_val       float64
security_name     object
cusip             object
dtype: object

In [22]:
df["portno"].dtype

dtype('O')

In [23]:
df["portno"]

0        2998623
1        2998623
2        2998623
3        2998623
4        2998623
          ...
99995    306412e
99996    306412e
99997    306412e
99998    306412e
99999    306412e
Name: portno, Length: 100000, dtype: object

In [24]:
df["portno"].unique()

array(['2998623', '2998638', '2998809', '2998821', '2999052', '2999757',
       '3000255', '300035d', '3001404', '3002313', '3002316', '300251d',
       '300283b', '3003702', '300383a', '3003846', '3004239', '300474c',
       '3005232', '3007017', '300783f', '3008148', '300814e', '3008151',
       '3008154', '3008157', '301242f', '3013614', '301370d', '301380c',
       '301421a', '3014637', '3014706', '301484a', '3015021', '3015330',
       '3026844', '302704b', '302740b', '302740e', '3029028', '302974e',
       '3029832', '3030108', '303010b', '3030138', '3030444', '3030510',
       '303054c', '3030828', '305112c', '3055317', '305531a', '305531d',
       '3055617', '3055905', '305623b', '305630d', '3056463', '305702a',
       '3058311', '3060003', '3060411', '3060414', '3060528', '3060531',
       '3060537', '3060540', '3060555', '306055e', '3060618', '306061b',
       '306061e', '3060630', '3060642', '3060645', '3060648', '3060654',
       '3060657', '3060702', '306070b', '3060711', '3060714', '306071a',
       '3060726', '306072c', '3060735', '3060738', '306073b', '3061116',
       '3061119', '306111c', '306111f', '3061122', '3061134', '3061155',
       '3061209', '306120c', '306121e', '3061227', '3061230', '3061236',
       '306123c', '306123f', '3061257', '306125d', '3061302', '3061314',
       '3061323', '306133e', '3061347', '306134a', '306140a', '306140d',
       '3061416', '306141c', '306144f', '306145e', '3061506', '3061509',
       '3061527', '306152d', '3061530', '3061533', '3061542', '3061551',
       '306155d', '3061563', '3061605', '3061608', '3061614', '306161a',
       '3061620', '3061623', '3061626', '3061629', '3061632', '3061662',
       '3061704', '3061707', '306170a', '3061719', '3061731', '3061734',
       '306173d', '3061740', '3061749', '306174f', '3061752', '3061758',
       '306175b', '306175e', '3061761', '3061800', '3061809', '3061815',
       '3061824', '3061830', '3061833', '3061836', '306184b', '306184e',
       '306185a', '3061911', '3061914', '3061938', '3061950', '3061953',
       '306195c', '3062004', '306200a', '3062016', '306201c', '3062025',
       '306202b', '306202e', '306203d', '3062040', '3062043', '3062046',
       '306204f', '3062052', '3062055', '3062058', '306205b', '3062136',
       '306213f', '3062145', '306214e', '3062154', '3062160', '3062163',
       '3062202', '3062205', '3062208', '306221a', '306221d', '3062223',
       '3062226', '3062232', '3062238', '306223b', '306223e', '3062244',
       '306224a', '306224d', '3062253', '306225f', '3062310', '3062349',
       '3062352', '3062403', '3062427', '306242a', '306242d', '3062430',
       '3062433', '3062436', '3062439', '306243c', '3062442', '306244b',
       '3062517', '3062556', '3062559', '306255c', '3062601', '3062607',
       '306260a', '306262e', '306263a', '3062640', '3062646', '3062661',
       '3062706', '3062712', '306271b', '306272d', '3062745', '306281a',
       '306281d', '3062835', '3062838', '306283b', '306283e', '3062841',
       '3062844', '3062847', '306284d', '3062850', '3062856', '3062901',
       '3062952', '306295b', '3062961', '3063006', '3063009', '306301e',
       '306311d', '3063120', '3063123', '306312c', '306312f', '3063141',
       '306314d', '3063156', '3063159', '306315c', '3063162', '306320d',
       '306321c', '306321f', '3063222', '3063225', '3063231', '3063234',
       '306323a', '306323d', '3063240', '306325b', '306325e', '3063309',
       '3063336', '3063339', '306333c', '306334e', '3063354', '306335a',
       '3063363', '3063402', '3063411', '3063444', '3063447', '3063453',
       '3063456', '3063459', '306345f', '3063462', '3063525', '306353d',
       '3063546', '3063603', '3063609', '306360c', '306360f', '3063612',
       '3063615', '3063618', '306362d', '3063639', '306363c', '306363f',
       '306364b', '306364e', '3063651', '3063654', '3063657', '306365a',
       '306370e', '3063717', '3063720', '306372c', '3063750', '3063756',
       '306380a', '3063813', '3063819', '306382b', '306382e', '3063831',
       '3063858', '306390c', '306390f', '3063912', '306392a', '3063930',
       '3063933', '3063936', '3063939', '3063948', '306394b', '306394e',
       '3064008', '3064011', '3064014', '3064017', '306401a', '306401d',
       '3064044', '3064050', '3064056', '3064059', '306405c', '306405f',
       '3064062', '3064101', '306410d', '3064116', '3064119', '306411c',
       '306411f', '3064122', '3064125', '3064128', '306412b', '306412e'],
      dtype=object)

In [25]:
df["portno"].unique().__len__()

366

In [29]:
df["portno"].nunique()

366

In [26]:
len(df["portno"].unique())

366

In [31]:
df["nbr_shares"].mean()

66273097.77758

In [33]:
df[["nbr_shares", "security_rank"]].mean()

nbr_shares       6.627310e+07
security_rank    1.370033e+03
dtype: float64

In [35]:
df["portno"].value_counts()

portno
3062442    9285
3062436    7676
3062403    3917
3062439    3311
3062352    3279
           ...
3063750       1
306201c       1
306070b       1
2999757       1
3061614       1
Name: count, Length: 366, dtype: int64

In [37]:
df.describe()

       security_rank    percent_tna    nbr_shares    market_val
count  100000.000000  100000.000000  1.000000e+05  1.000000e+05
mean     1370.033410       0.278084  6.627310e+07  6.621190e+06
std      2006.655863       1.864025  3.099766e+09  4.122161e+07
min         1.000000    -101.000000 -8.451950e+10 -4.798583e+09
25%       165.000000       0.010000  3.517325e+04  1.515223e+05
50%       565.000000       0.030000  2.763050e+05  6.662634e+05
75%      1657.000000       0.140000  1.360000e+06  3.256665e+06
max      9290.000000     100.290000  2.950900e+11  4.901722e+09

In [38]:
df.head()

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10

In [41]:
df.tail(3)

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
99997,306412e,2020/12/31,171,2021/01/08,0.07,12000000.0,14594147.0,Massachusetts School Building Authority 5% 15-...,576000YJ
99998,306412e,2020/12/31,173,2021/01/08,0.07,11485000.0,14497554.0,Massachusetts Water Resources Authority 5% 01-...,576051PH
99999,306412e,2020/12/31,174,2021/01/08,0.07,12655000.0,14493687.0,Contra Costa Community College District 5% 01-...,212204HD

In [39]:
df["portno"] == "2998623"

0         True
1         True
2         True
3         True
4         True
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Name: portno, Length: 100000, dtype: bool

In [40]:
portno_filter = df["portno"] == "2998623"
df[portno_filter]
df[df["portno"] == "2998623"]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
346,2998623,2020/11/30,352,2021/01/08,0.00,1303.0,1.594570e+03,Ginnie Mae 2 20-JAN-2031 003028,36202DLH
347,2998623,2020/11/30,352,2021/01/08,0.00,3702.0,3.726940e+03,Gvt Ntl Mrtg Asn 15-Jun-2026 422949,36206VZN
348,2998623,2020/11/30,352,2021/01/08,0.00,5645.0,5.665600e+03,Fannie Mae 01-Jul-2032 642656,31390C5R
349,2998623,2020/11/30,352,2021/01/08,0.00,1.0,1.070000e+00,Fannie Mae 01-MAR-2021 866003 Pd Down,31409BDG
350,2998623,2020/11/30,352,2021/01/08,0.00,0.0,6.370000e+00,VIATRIS INC,92556V10

In [42]:
columns = ["Name", "Age", "Height"]
data = [
		["Ted", 24, 177],
		["Judy", 27, 183],
]
df2 = pd.DataFrame(data=data, columns=columns)
df2

   Name  Age  Height
0   Ted   24     177
1  Judy   27     183

In [44]:
df2["Name"] == "Ted"

0     True
1    False
Name: Name, dtype: bool

In [43]:
"""
select name, age, hight from df2 where name = 'Ted';
"""

df2[df2["Name"] == "Ted"]

  Name  Age  Height
0  Ted   24     177

In [48]:
portno_filter = df["portno"] == "2998623"
share_percentage_filter = df["percent_tna"] < 1

In [49]:
df[portno_filter & share_percentage_filter]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
32,2998623,2020/11/30,33,2021/01/08,0.97,2350480.0,1.180881e+08,COMCAST CORP NEW,20030N10
33,2998623,2020/11/30,34,2021/01/08,0.94,724928.0,1.148431e+08,N X P SEMICONDUCTORS N V,N6596X10
34,2998623,2020/11/30,35,2021/01/08,0.94,3616628.0,1.138514e+08,US FOODS HOLDING CORP,91200810
35,2998623,2020/11/30,36,2021/01/08,0.91,2015089.0,1.109710e+08,CITIGROUP INC,17296742
36,2998623,2020/11/30,37,2021/01/08,0.88,596059.0,1.072370e+08,MCKESSON H B O C INC,58155Q10
...,...,...,...,...,...,...,...,...,...
346,2998623,2020/11/30,352,2021/01/08,0.00,1303.0,1.594570e+03,Ginnie Mae 2 20-JAN-2031 003028,36202DLH
347,2998623,2020/11/30,352,2021/01/08,0.00,3702.0,3.726940e+03,Gvt Ntl Mrtg Asn 15-Jun-2026 422949,36206VZN
348,2998623,2020/11/30,352,2021/01/08,0.00,5645.0,5.665600e+03,Fannie Mae 01-Jul-2032 642656,31390C5R
349,2998623,2020/11/30,352,2021/01/08,0.00,1.0,1.070000e+00,Fannie Mae 01-MAR-2021 866003 Pd Down,31409BDG
350,2998623,2020/11/30,352,2021/01/08,0.00,0.0,6.370000e+00,VIATRIS INC,92556V10

In [51]:
"""
select *
from df
where portno = '2998623'
    and (
        percent_tna > 2 or percent_tna < 0.3
    )
"""

portno_filter = df["portno"] == "2998623"
share_percentage_filter_1 = df["percent_tna"] > 2
share_percentage_filter_2 = df["percent_tna"] < 0.3

df[portno_filter & (share_percentage_filter_1 | share_percentage_filter_2)]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
93,2998623,2020/11/30,94,2021/01/08,0.29,34380000.0,3.509063e+07,Nestle Holdings Inc 3.1% 24-SEP-2021,641062AJ
94,2998623,2020/11/30,95,2021/01/08,0.27,20265000.0,3.232174e+07,Cree Inc .875% 01-SEP-2023,225447AB
95,2998623,2020/11/30,96,2021/01/08,0.27,505265.0,3.229149e+07,KELLOGG CO,48783610
96,2998623,2020/11/30,97,2021/01/08,0.26,31406000.0,3.141827e+07,US Treasury 0.625% 30-Nov-2027,91282CAY
...,...,...,...,...,...,...,...,...,...
346,2998623,2020/11/30,352,2021/01/08,0.00,1303.0,1.594570e+03,Ginnie Mae 2 20-JAN-2031 003028,36202DLH
347,2998623,2020/11/30,352,2021/01/08,0.00,3702.0,3.726940e+03,Gvt Ntl Mrtg Asn 15-Jun-2026 422949,36206VZN
348,2998623,2020/11/30,352,2021/01/08,0.00,5645.0,5.665600e+03,Fannie Mae 01-Jul-2032 642656,31390C5R
349,2998623,2020/11/30,352,2021/01/08,0.00,1.0,1.070000e+00,Fannie Mae 01-MAR-2021 866003 Pd Down,31409BDG
350,2998623,2020/11/30,352,2021/01/08,0.00,0.0,6.370000e+00,VIATRIS INC,92556V10

In [53]:
df.groupby("portno").size()

portno
2998623    351
2998638     77
2998809     70
2998821     54
2999052      2
          ...
3064122     28
3064125     27
3064128     27
306412b     28
306412e    174
Length: 366, dtype: int64

In [54]:
df.groupby("portno").sum()

,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
portno,,,,,,,,
2998623,2020/11/302020/11/302020/11/302020/11/302020/1...,61888,2021/01/082021/01/082021/01/082021/01/082021/0...,99.79,3.817768e+09,1.213476e+10,GENERAL MOTORS COCOGNIZANT TECHNOLOGY SOLS COR...,37045V1019244610617446447181721022052L1038141G...
2998638,2020/11/302020/11/302020/11/302020/11/302020/1...,3021,2021/01/082021/01/082021/01/082021/01/082021/0...,99.89,4.856478e+08,8.460393e+09,CITIGROUP INCBANK OF AMERICA CORPPHILIP MORRIS...,17296742060505107181721037045V1061744644026874...
2998809,2020/11/302020/11/302020/11/302020/11/302020/1...,2485,2021/01/082021/01/082021/01/082021/01/082021/0...,99.50,1.312320e+08,1.989293e+09,JPMORGAN CHASE & COState Street US Government ...,46625H1085749270369604100605051084265V10247361...
2998821,2020/11/302020/11/302020/11/302020/11/302020/1...,1485,2021/01/082021/01/082021/01/082021/01/082021/0...,100.01,7.659816e+07,1.721541e+09,SCIENCE APPLICATIONS INTL CORPPARSLEY ENERGY I...,808625107018771029261A10G515021087603010497266...
2999052,2020/10/312020/10/31,634,2021/01/082021/01/08,0.08,8.600000e+05,8.558093e+05,Hewlett Packard Enterprise Co .954% 05-OCT-202...,42824CBB345397YY
...,...,...,...,...,...,...,...,...
3064122,2020/11/302020/11/302020/11/302020/11/302020/1...,406,2021/01/082021/01/082021/01/082021/01/082021/0...,99.12,4.468253e+07,4.893021e+08,MML Managed Bond Fund;InitialMML Dynamic Bond ...,55312G3055312G68553097665530971955312G75553097...
3064125,2020/11/302020/11/302020/11/302020/11/302020/1...,378,2021/01/082021/01/082021/01/082021/01/082021/0...,99.88,1.692612e+08,1.883633e+09,MML Managed Bond Fund;InitialMML Dynamic Bond ...,55312G3055312G68553097665530971955309769553097...
3064128,2020/11/302020/11/302020/11/302020/11/302020/1...,378,2021/01/082021/01/082021/01/082021/01/082021/0...,99.58,1.159768e+08,1.299732e+09,MML Global Fund;IMML Managed Bond Fund;Initial...,5530976655312G30553097195530977455309769553097...
306412b,2020/11/302020/11/302020/11/302020/11/302020/1...,406,2021/01/082021/01/082021/01/082021/01/082021/0...,99.90,1.390335e+07,1.561399e+08,MML Global Fund;IMML Focused Equity Fund;IIMML...,5530976655309719553097695530977455309776553097...
306412e,2020/12/312020/12/312020/12/312020/12/312020/1...,15180,2021/01/082021/01/082021/01/082021/01/082021/0...,18.02,3.225175e+09,3.693306e+09,"BlackRock Liquidity MuniCash;InstTexas, State ...",09248U84882723ZQ249164QW212204HZ20772JD864972G...

In [55]:
df.groupby("portno")["security_rank"].sum()

portno
2998623    61888
2998638     3021
2998809     2485
2998821     1485
2999052      634
           ...
3064122      406
3064125      378
3064128      378
306412b      406
306412e    15180
Name: security_rank, Length: 366, dtype: int64

In [56]:
df.groupby("portno").get_group("3064128")

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
99771,3064128,2020/11/30,1,2021/01/08,9.94,9765061.0,1.297777e+08,MML Global Fund;I,55309766
99772,3064128,2020/11/30,2,2021/01/08,8.01,7746025.0,1.045778e+08,MML Managed Bond Fund;Initial,55312G30
99773,3064128,2020/11/30,3,2021/01/08,7.12,13199236.0,9.292262e+07,MML Focused Equity Fund;II,55309719
99774,3064128,2020/11/30,4,2021/01/08,6.31,4113822.0,8.231758e+07,MML Blue Chip Growth Fund;Initial,55309774
99775,3064128,2020/11/30,5,2021/01/08,6.21,4688809.0,8.111640e+07,MML Mid Cap Growth Fund;Initial,55309769
99776,3064128,2020/11/30,6,2021/01/08,5.23,6923092.0,6.826169e+07,MML Equity Income Fund;Initial,55309777
99777,3064128,2020/11/30,7,2021/01/08,5.06,6933361.0,6.607493e+07,MML Income & Growth Fund;Initial,55309776
99778,3064128,2020/11/30,8,2021/01/08,4.87,6174860.0,6.360106e+07,MML Mid Cap Value Fund;Initial,55309771
99779,3064128,2020/11/30,9,2021/01/08,4.80,5603503.0,6.259113e+07,MML Fundamental Value Fund;II,55309721
99780,3064128,2020/11/30,10,2021/01/08,4.42,6202114.0,5.767966e+07,MML International Equity Fund;II,55309715
99781,3064128,2020/11/30,11,2021/01/08,4.24,5338023.0,5.535530e+07,MML Dynamic Bond Fund;Class 2,55312G68
99782,3064128,2020/11/30,12,2021/01/08,4.22,5296918.0,5.508795e+07,MML Fundamental Equity Fund;II,55309717
99783,3064128,2020/11/30,13,2021/01/08,3.97,4602707.0,5.178046e+07,MML Total Return Bond Fund,NaN
99784,3064128,2020/11/30,14,2021/01/08,3.81,5250605.0,4.967072e+07,MML Foreign Fund;Initial,55309765
99785,3064128,2020/11/30,15,2021/01/08,3.71,4304801.0,4.847206e+07,MML Inflation-Protected & Income Fund;Initial,55312G20
99786,3064128,2020/11/30,16,2021/01/08,3.71,3578610.0,4.838281e+07,MML Strategic Emerging Markets Fund;Svc Class 1,55312G79
99787,3064128,2020/11/30,17,2021/01/08,2.54,3388225.0,3.313684e+07,MML Short-Duration Bond Fund;Class 2,55312G75
99788,3064128,2020/11/30,18,2021/01/08,2.31,2219908.0,3.014635e+07,MML Large Cap Growth;Initial,55309773
99789,3064128,2020/11/30,19,2021/01/08,1.84,1708447.0,2.403785e+07,MML Small Company Value Fund;II,55309726
99790,3064128,2020/11/30,20,2021/01/08,1.45,1839446.0,1.889111e+07,MML Small/Mid Cap Value Fund;Initial,55309768
99791,3064128,2020/11/30,21,2021/01/08,1.44,376801.0,1.877599e+07,Invesco Oppenheimer VI Global Fund;I,00900X50
99792,3064128,2020/11/30,22,2021/01/08,1.28,1704277.0,1.677009e+07,MML High Yield Fund;Class 2,55312G73
99793,3064128,2020/11/30,23,2021/01/08,1.13,957508.0,1.471529e+07,MML Small Cap Growth Equity Fund;Initial,55309720
99794,3064128,2020/11/30,24,2021/01/08,1.09,3026916.0,1.425677e+07,Invesco Oppenheimer VI Global Strategic Income;I,00900X88
99795,3064128,2020/11/30,25,2021/01/08,0.36,166407.0,4.644412e+06,MML Equity Index Fund;II,55309783
99796,3064128,2020/11/30,26,2021/01/08,0.34,43843.0,4.414142e+06,Invesco Oppenheimer VI Discovery Mid Cap Growth;I,00900X75
99797,3064128,2020/11/30,27,2021/01/08,0.17,823516.0,2.272905e+06,Invesco Oppenheimer VI International Growth Fd;I,00900X84